#!/usr/bin/python
Path = ""
# Add folders
FileList = []
# Add list of File
import os
# import system 

def SearchFiles(FolderPath):
    FolderOrDocuments = os.listdir(FolderPath)
    for a in FolderOrDocuments:
        FullPath = os.path.join(FolderPath,a)
        if os.path.isdir(FullPath):
            SearchFile(FullPath)
        else:
            print(a)
            global FileList
            FileList.append(a)

SearchFiles(path)
print(FileList)
